### PR TITLE
Update syscall definitions

### LINKED ISSUE #222: Const syscall names for new arches in 0.4.0

### PR DESCRIPTION
**Pull request by rusty-snake**
Fixes #222

### CODE REVIEW

**Comment by ManaSugi** [comment]
@rusty-snake Thanks!

Is it possible to add the test in [the CI](https://github.com/libseccomp-rs/libseccomp-rs/blob/main/.github/workflows/build-test.yaml#L95) using the following target?

https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html
https://doc.rust-lang.org/rustc/platform-support/m68k-unknown-linux-gnu.html

**Comment by ManaSugi** [comment]
Besides, we need to add the architectures to https://github.com/libseccomp-rs/libseccomp-rs/blob/main/libseccomp/src/syscall.rs#L13

**Comment by rusty-snake** [comment]
> Is it possible to add the test in [the CI](https://github.com/libseccomp-rs/libseccomp-rs/blob/main/.github/workflows/build-test.yaml#L95) using the following target?

Both are Tier-3 and have no official build of the toolchain.

**Comment by ManaSugi** [comment]
> > Is it possible to add the test in [the CI](https://github.com/libseccomp-rs/libseccomp-rs/blob/main/.github/workflows/build-test.yaml#L95) using the following target?
> 
> Both are Tier-3 and have no official build of the toolchain.

Maybe, we can add the tier-3 target as follows.

```
rustup +nightly component add rust-src
cargo build -Z build-std --target loongarch64-unknown-linux-gnu
```

**Comment by rusty-snake** [comment]
According to [this table](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3) loongarch64 has only support for `no_std`.

**Comment by ManaSugi** [comment]
I could cross-compile the libseccomp-rs with loongarch on the `x86_64-unknown-linux-gnu` host.
```sh
rustup +nightly target add loongarch64-unknown-linux-gnu
cargo +nightly build -Z build-std --target loongarch64-unknown-linux-gnu
```
Ref. https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html#cross-compilation

So we can add the test to our CI.

**Comment by rusty-snake** [comment]
But do we want to build all targets with nightly in this job?

**Comment by ManaSugi** [comment]
No, we can just use as follows.

```sh

if [[ ${{ matrix.target }} == "loongarch64-unknown-linux-gnu" ]]; then
    rustup +nightly target add ${{ matrix.target }}
    cargo +nightly build -Z build-std --target ${{ matrix.target }} 
fi
```

**Comment by rusty-snake** [comment]
Rust 1.71: Promote `loongarch64-unknown-linux-gnu` to Tier 2 with host tools

**Comment by rusty-snake** [comment]
@ManaSugi this way it passes CI now. But I can not say why/what it does/if things are good.

**Comment by ManaSugi** [comment]
@rusty-snake Thanks!

Regarding m68k, we can compile it using  `qemu` user emulation as mentioned in the doc.
https://doc.rust-lang.org/rustc/platform-support/m68k-unknown-linux-gnu.html

Could you try it in our CI?

**Comment by ManaSugi** [comment]
> But I can not say why/what it does/if things are good.

The purpose of the test for the cross compilation is to check #[cfg(target_arch = "***")] is correct and `syscall/***.rs` can be complied without failure. if the `target_arch` or `syscall/***.rs`  have some wrong (e.g., typo), the build failure occurs.

**Comment by rusty-snake** [comment]
https://github.com/search?q=m68k-unknown-linux-gnu+path%3A.github%2F++&type=code
https://github.com/rust-lang/rust/issues/89498

Don't known if it is worth the try. Sounds like it would fail.

**Comment by ManaSugi** [comment]
> https://github.com/search?q=m68k-unknown-linux-gnu+path%3A.github%2F++&type=code
https://github.com/rust-lang/rust/issues/89498
> Don't known if it is worth the try. Sounds like it would fail.

Oh, thanks for the information. Beside, I tried it on my environment, but setting up the m68k took long time and I expect this will take much longer on the CI (the resource is very limited). Let's skip the m68k.

Could you add the comment to `m68k` target as follows?

```rust
#- m68k-unknown-linux-gnu # It is unavailable even in channel 'nightly'.
```

**Review by ManaSugi — APPROVED** [review]
LGTM, thanks @rusty-snake !

**Pull request merged**
