### PR TITLE
Add config for dependabot

### PR DESCRIPTION
**Pull request by ManaSugi**
Add a config file for the dependabot in order to enable it to analyze the crate version.

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Comment by rusty-snake** [comment]
What will it do?

**Comment by ManaSugi** [comment]
@rusty-snake Sorry for my poor explanation.

We can use the dependabot to ensure that our libseccomp-rs repository automatically keeps up with the latest releases of the crates it depends on. This version updates are automated pull requests that keep our dependencies updated, even when they don’t have any vulnerabilities.  Regarding the `libseccomp` crate, we can keep up with the latest releases of the `libc`, `bitflags` and `pkg-config` without checking by hand.

Ref. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

**Comment by rusty-snake** [comment]
We do not commit Cargo.lock files (as it is recommend for libraries) which pin our dependencies to a specific version (= use dependabot). We only specify dependencies in Cargo.toml where cargo the chooses the best matching version that is semver-compatible with this version (usually the newest semver-compatible version). AFAIK dependabot does not open PRs for semver-incompatible updates.

**Comment by ManaSugi** [comment]
> AFAIK dependabot does not open PRs for semver-incompatible updates.

I think dependabot opens PR even if the updated version is incompatible as long as we do not specify [ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore).

**Review by rusty-snake — APPROVED** [review]
You seem to be right, LGTM.

**Pull request merged**
