### PR TITLE
Move types into own modules

### PR DESCRIPTION
**Pull request by rusty-snake**
Move types into own modules to keep files short and clear.

No public API changes.

ScmpSyscall is excluded ATM to avoid merge conflicts.

### CODE REVIEW

**Comment by ManaSugi** [comment]
@rusty-snake  Thank you!. Do we need the `scmp_` prefix for each file name? I prefer using just `action.rs`, `arch.rs`, etc because they are redundant.

**Comment by rusty-snake** [comment]
Actually I named them after the type (UpperCamelCase -> snake_case). The advantage of a `scmp_` prefix is that the names for these modules look different form `notify`/`error`. But in the end I don't care. I can also change it if you want.

**Comment by ManaSugi** [comment]
I understand. However, from this PR, I'm thinking about whether to re-export `notify` module using `pub use` like this PR as follows.

```rust
#[cfg(any(libseccomp_v2_5, doc))] 
pub mod notify; 
...
#[cfg(any(libseccomp_v2_5, doc))
pub use notify::*;              
```

Considering this, it would be better not to use `scmp_` prefix to keep consistent. What do you think?

**Comment by rusty-snake** [comment]
I will remove it.

**Comment by ManaSugi** [comment]
LGTM. Thank you so much! @rusty-snake

**Review by ManaSugi — APPROVED** [review]

**Pull request merged**
