### PR TITLE
`seccomp_export_bpf_mem`

### LINKED ISSUE #121: `seccomp_export_bpf_mem`
Upstream commit: https://github.com/seccomp/libseccomp/commit/3f0e47fe2717b73ccef68ca18f9f7297ee73ebb2 (not release yet)

`libseccomp-sys`:
```rust
extern "C" {
    /// Generate seccomp Berkeley Packet Filter (BPF) code and export it to a buffer
    ///
    /// - `ctx`: the filter context
    /// - `buf`: the destination buffer
    /// - `len`: on input the length of the buffer, on output the number of bytes in the program
    ///
    /// This function generates seccomp Berkeley Packer Filter (BPF) code and writes
    /// it to the given buffer.  Returns zero on success, negative values on failure.
    pub fn seccomp_export_bpf_mem(ctx: const_scmp_filter_ctx, buf: *mut /* FIXME */, len: *mut c_size_t) -> c_int;
}
```

`libseccomp`:
```rust
impl ScmpFilterContext {
    pub fn export_bpf_mem(&self) -> Vec<u8> {
        ...
    }
}
```

### PR DESCRIPTION
**Pull request by rusty-snake**
Fixes #121

ToDo:

- [x] Where should the cfg go? The function, Separated `impl`, Separated `impl` in new module.

### CODE REVIEW

**Comment by ManaSugi** [comment]
> I'm going to prefer separate `impl`-blocks for new functions.
> 
> ```rust
> impl Scmp {
>     // >=2.5.0 (min supported by us)
> }
> #[cfg(libseccomp_2_6_0)]
> impl Scmp {
>     // >=2.6.0
> }
> ```

Looks good! Considering adding new apis in the future, it makes sense.

**Comment by rusty-snake** [comment]
CI seems to pass now.

Release reminder: Check the `cfg`ed section on docs.rs.

**Comment by ManaSugi** [comment]
@rusty-snake 

Is this necessary?
`all(doc, not(doctest))`

Without the attribute, I can pass the all tests on my environment (libseccomp v2.5.4)

**Comment by ManaSugi** [comment]
Oops, I failed, Sorry

**Comment by rusty-snake** [comment]
FTR

> `libseccomp_v2_6 or (doc and not doctest)`

We want to include the `impl` block if
- compiling against libseccomp>=2.6
- testing against libseccomp>=2.6
- generating documentations (for docs.rs)
but not if we run doctests with libseccomp<2.6

**Review by ManaSugi — APPROVED** [review]
LGTM, thanks @rusty-snake !

**Pull request merged**
