### PR TITLE
Release v0.3.x cherry pick suggestions (1/x)

### PR DESCRIPTION
**Pull request by rusty-snake**
That are the easy ones. We likely want

- ci with 2.5.5
- cf98d807cdd36da117f9aca9810b584892d1084f
- 17288dc05913360958029b8bd328e8ec65e54a22
- 50a82ad0ff33be65953a94ec880d6bcc34f3dad1
- 2dd8461b3d8ca825018efd779ee42588df709b5b
- ~~1081f1c82adf70dc763933e1f5be06ee56829ef5~~ included to fix ci
- ... ???
- update CHANGELOG.md

too.

- Removed 4daf545 from the list because it breaks with Rust 1.46.

### CODE REVIEW

**Comment by ManaSugi** [comment]
@rusty-snake Thanks! 

Would it better to release v0.3.x before v0.4.0?

**Comment by rusty-snake** [comment]
Random unordered thought:
- 0.3.x will have bug fixes, semver compatible minor improvments, updated **syscalls from libseccomp 2.5.5** that are already used by glibc
- 0.4.0 (based on our main) will have all the bug fixes, all the breaking changes and improvments, updated **syscalls from libseccomp-main (2.6.0)**, new library functions from libseccomp-main (2.6.0) like `precompute`.
- I do not want to release an api (`precompute`, ...) that has no stable release upstream. It is less useful as you need to build libseccomp from git to use them. It requires a new semver bump if upstream has to make a breaking fix found in QA.
- I want to release bug fixes from the last year and show some release activity.
- I want to release syscall definitions for syscalls used by glibc.
- I'm scared because **the syscall definitions** (pseudo numbers) **between libseccomp 2.5.5 and libseccomp-main (2.6.0) are incompatible**. `-10245` is [`__PNR_map_shadow_stack`](https://github.com/seccomp/libseccomp/blob/v2.5.5/include/seccomp-syscalls.h) in 2.5.5 but [`__PNR_fstat`](https://github.com/seccomp/libseccomp/blob/main/include/seccomp-syscalls.h) in main. They have a diverging api.

**Comment by ManaSugi** [comment]
@rusty-snake Okay, let's release v.0.3.1.
As you mentioned, it has been a long time, more than 1 year, since v0.3.0 was released, so considrering the fact, we should release v0.3.1 including bug fixes. It is difficult for us to expect when the libseccomp v2.6.0 will be released and not good to wait for it to be done with remaing known bugs.  Thanks for your suggestion!

**Review by ManaSugi — APPROVED** [review]

**Comment by rusty-snake** [comment]
> This PR seems to include necessary commits for v0.3.1. LGTM!

Mostly, a few are missing like https://github.com/libseccomp-rs/libseccomp-rs/commit/50a82ad0ff33be65953a94ec880d6bcc34f3dad1 see OP.

**Comment by ManaSugi** [comment]
@rusty-snake Oh, yes, sorry, could you re-create a pull request to have all expected fixes such as https://github.com/libseccomp-rs/libseccomp-rs/pull/255,  https://github.com/libseccomp-rs/libseccomp-rs/commit/50a82ad0ff33be65953a94ec880d6bcc34f3dad1, and etc. for the `release/v0.3.x` branch?

I rebased and pushed forcibly the `release/v0.3x` before this commit is merged.  The force rebase and push shouldn't be done but I'd like to keep the same order of commits of the `release/v0.3.x` as that of the main so that we can see our commit history easily.

**Pull request merged**
